rulebook:
  content: []

stickmenu:
  enabled: true
  stick-interact: true

  profile:
    disable-vault: true
    disable-lp-group: true
    disable-lp-rank: true

server-list:
  enabled: true
  stick-interact: true

  size: 54
  servers:
    - position: 0
      material: COMPASS
      name: "ロビー"
      lore: []
      enchant: false
      custom-model-data: 0

      goto: lobby