name: "NekoHub"
version: ${version}

author: Taitaitatata
description: ${description}
website: ${website}

api-version: 1.16
main: net.nekozouneko.nekohub.spigot.SpigotNekoHubPlugin

softdepend: ["LuckPerms"]

commands:
  stickmenu:
    aliases: ["sm", "menu", "m"]
    description: "棒メニューを開きます。"
    permission: nekohub.command.stickmenu
    usage: "/<command> [target...]"
  serverlist:
    aliases: ["sl", "servers"]
    description: "サーバーリストを開きます。"
    permission: nekohub.command.serverlist
    usage: "/<command> [target...]"
  rulebook:
    aliases: ["rule", "readme"]
    description: "ルールブックを開きます。"
    permission: nekohub.command.rulebook
    usage: "/<command>"
  stick:
    aliases: ["s"]
    description: "棒を入手します。"
    permission: nekohub.command.stick
    usage: "/<command>"
  server:
    permission: nekohub.command.server
    usage: "/<command> <server> [player]"
  hub:
    aliases: ["lobby"]
    permission: nekohub.command.hub
    usage: "/<command>"
  nekohub:
    aliases: ["nh"]
    permission: nekohub.command.nekohub
    usage: "/<command> reload"
  trash:
    aliases: ["trashbox", "tb", "gomi"]
    permission: nekohub.command.trash
    usage: "/<command> [target...]"
  bed:
    aliases: ["bed-spawn", "my-bed"]
    permission: nekohub.command.bed
    usage: "/<command>"
  enderchest:
    aliases: ["ec", "ender"]
    permission: nekohub.command.enderchest
    usage: "/<command>"
  spawn:
    aliases: ["world-spawn", "server-spawn"]
    permission: nekohub.command.spawn
    usage: "/<command>"
  suicide:
    permission: nekohub.command.suicide
    usage: "/<command>"

default-permission: true

permissions:
  nekohub:
    default: op
    children:
      nekohub.stickmenu.open: true

  nekohub.command:
    default: op
    children:
      nekohub.command.stickmenu: true
      nekohub.command.stickmenu.other: true
      nekohub.command.serverlist: true
      nekohub.command.serverlist.other: true
      nekohub.command.rulebook: true
      nekohub.command.stick: true
      nekohub.command.nekohub: true
      nekohub.command.hub: true
      nekohub.command.server: true
      nekohub.command.server.other: true
      nekohub.command.trash: true
      nekohub.command.trash.other: true
      nekohub.command.bed: true
      nekohub.command.enderchest: true
      nekohub.command.spawn: true
      nekohub.command.suicide: true

  nekohub.command.stickmenu:
    default: true

  nekohub.command.stickmenu.other:
    default: op

  nekohub.command.serverlist:
    default: true

  nekohub.command.serverlist.other:
    default: op

  nekohub.command.rulebook:
    default: true

  nekohub.command.stick:
    default: true

  nekohub.command.nekohub:
    default: op

  nekohub.command.hub:
    default: true

  nekohub.command.server:
    default: op

  nekohub.command.server.other:
    default: op

  nekohub.command.trash:
    default: true

  nekohub.command.trash.other:
    default: op

  nekohub.command.bed:
    default: true

  nekohub.command.enderchest:
    default: true

  nekohub.command.spawn:
    default: true

  nekohub.command.suicide:
    default: true

  nekohub.interact:
    default: op
    children:
      nekohub.interact.stickmenu: true
      nekohub.interact.serverlist: true

  nekohub.interact.stickmenu:
    default: true

  nekohub.interact.serverlist:
    default: true